# Generated by Django 4.1 on 2022-09-01 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=500, verbose_name='Fournisseur')),
                ('num', models.CharField(max_length=255, verbose_name='n bon de livraison')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantite')),
                ('date_livraison', models.DateField(verbose_name='date livraison')),
                ('date_exp', models.DateField(null=True, verbose_name='Date exp.')),
                ('observation', models.CharField(blank=True, max_length=500, null=True, verbose_name='observation')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='categorie')),
            ],
        ),
        migrations.CreateModel(
            name='EtatCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=255, verbose_name='Etat Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='partenaire')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='programme')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Province')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Site')),
            ],
        ),
        
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500, verbose_name='desigantion')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicaments.categorie', verbose_name='produit')),
                ('programme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medicaments.programme', verbose_name='programme')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lot', models.CharField(max_length=255, null=True, verbose_name='Num lot')),
                ('date_estime_livraison', models.DateField(null=True, verbose_name='Date estime livraison')),
                ('quantite', models.PositiveIntegerField(verbose_name='quantite')),
                ('prix_unitaire', models.PositiveIntegerField(verbose_name='prix unitaire(BIF)')),
                ('date_exp', models.DateField(null=True, verbose_name='Date exp.')),
                ('etat_commande', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicaments.etatcommande', verbose_name='Etat commande')),
                ('partenaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medicaments.partenaire', verbose_name='partenaire')),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medicaments.produit', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='DistrMoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2022)], verbose_name='annee')),
                ('value', models.PositiveIntegerField(verbose_name='Distr. moyenne annuelle')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='ConsMoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2022)], verbose_name='annee')),
                ('value', models.PositiveIntegerField(verbose_name='cons. moyenne annuel')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit', verbose_name='produit')),
            ],
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.lot'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        
        migrations.CreateModel(
            name='CVBonLivraison',
            fields=[
                ('bonlivraison_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medicaments.bonlivraison')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.site')),
            ],
            bases=('medicaments.bonlivraison', models.Model),
        ),
        
        migrations.CreateModel(
            name='CBonLivraison',
            fields=[
                ('bonlivraison_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medicaments.bonlivraison')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.province')),
            ],
            bases=('medicaments.bonlivraison', models.Model),
        ),
    ]
