# Generated by Django 4.1 on 2022-09-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='num_lot',
        ),
        migrations.AddField(
            model_name='lot',
            name='ref_commande',
            field=models.CharField(max_length=255, null=True, verbose_name='Ref Commande'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='livraison',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='medicaments.bonlivraison', verbose_name='Stock'),
        ),
    ]
