# Generated by Django 4.1 on 2022-09-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0003_remove_lot_num_lot_lot_ref_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='num_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Ref'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='etat_commande',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicaments.etatcommande', verbose_name='Etat commande'),
        ),
    ]
