# Generated by Django 4.1 on 2022-09-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0004_produit_num_ref_alter_lot_etat_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sage', models.PositiveIntegerField(verbose_name='quantite Sage')),
                ('mois', models.CharField(choices=[('1', 'janvier'), ('2', 'Fevrier'), ('3', 'Mars'), ('4', 'Avril'), ('5', 'Mai'), ('6', 'Juin'), ('7', 'Juillet'), ('8', 'Aout'), ('9', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], max_length=255)),
                ('annee', models.CharField(choices=[('2022', '2022'), ('2021', '2021')], max_length=255)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.bonlivraison', verbose_name='Stock Sage')),
            ],
        ),
    ]
