# Generated by Django 4.1 on 2022-09-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0005_stocksage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lot',
            new_name='Commande',
        ),
        migrations.RenameField(
            model_name='bonlivraison',
            old_name='lot',
            new_name='commande',
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='num',
            field=models.CharField(max_length=255, verbose_name='Num lot'),
        ),
        migrations.AlterField(
            model_name='stocksage',
            name='livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.bonlivraison', verbose_name='Commande'),
        ),
    ]
