# Generated by Django 4.1 on 2022-09-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0007_alter_produit_options_produit_dashbord'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventaireSage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=255)),
                ('quantite_sage', models.PositiveIntegerField(verbose_name='quantite Sage')),
                ('mois', models.CharField(choices=[('01', 'janvier'), ('02', 'Fevrier'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Aout'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], max_length=255)),
                ('annee', models.CharField(choices=[('2022', '2022'), ('2021', '2021')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_estime_livraison',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='etat_commande',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ref_commande',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='gestionnaire',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='livraison',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='num_sortie',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(null=True, verbose_name='Date livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='observation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='observation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produit_commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medicaments.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite_commande',
            field=models.PositiveIntegerField(null=True, verbose_name='quantite'),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille_paquet',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sortie',
            name='produit_sortie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medicaments.produit', verbose_name='produit'),
        ),
        migrations.DeleteModel(
            name='StockSage',
        ),
        migrations.AddField(
            model_name='inventairesage',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit', verbose_name='Produit'),
        ),
    ]
