# Generated by Django 4.1 on 2022-09-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0008_inventairesage_remove_commande_date_estime_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicaments.categorie', verbose_name='categorie'),
        ),
    ]
