# Generated by Django 4.1 on 2022-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0010_commande_lot_commande_sortie_lot_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventairesage',
            old_name='produit',
            new_name='produit_inventaire',
        ),
        migrations.AddField(
            model_name='inventairesage',
            name='prix_unitaire_sage',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix Unitaire'),
        ),
    ]
