# Generated by Django 4.1 on 2022-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0011_rename_produit_inventairesage_produit_inventaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairesage',
            name='date_exp',
            field=models.DateField(null=True, verbose_name='Date exp.'),
        ),
    ]
