# Generated by Django 4.1 on 2022-10-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0013_classification_produit_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrMoyReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2022)], verbose_name='annee')),
                ('mois', models.PositiveIntegerField(choices=[('01', 'janvier'), ('02', 'Fevrier'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Aout'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], verbose_name='mois')),
                ('value', models.PositiveIntegerField(verbose_name='Distr. moyenne annuelle')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit', verbose_name='produit')),
            ],
        ),
        migrations.CreateModel(
            name='ConsMoyReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2022)], verbose_name='annee')),
                ('mois', models.PositiveIntegerField(choices=[('01', 'janvier'), ('02', 'Fevrier'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Aout'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], verbose_name='mois')),
                ('value', models.PositiveIntegerField(verbose_name='cons. moyenne mens. reel')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit', verbose_name='produit')),
            ],
        ),
    ]
