# Generated by Django 4.1 on 2022-10-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0014_distrmoyreel_consmoyreel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='conditionnement')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='dosage')),
            ],
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='formulation')),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taille_paquet',
        ),
        migrations.AddField(
            model_name='produit',
            name='abbreviation',
            field=models.CharField(default='', max_length=255, verbose_name='abreviation'),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditionnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicaments.conditionnement', verbose_name='conditionnement'),
        ),
        migrations.AddField(
            model_name='produit',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicaments.dosage', verbose_name='dosage'),
        ),
        migrations.AddField(
            model_name='produit',
            name='formulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicaments.formulation', verbose_name='formulation'),
        ),
    ]
