# Generated by Django 4.1 on 2022-10-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0016_alter_produit_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventairesage',
            name='lot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
