# Generated by Django 4.1 on 2022-10-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0017_alter_inventairesage_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_exp',
        ),
    ]
