# Generated by Django 4.1 on 2022-10-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0018_remove_commande_date_exp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consmoy',
            options={'verbose_name': 'Besoin annuel previsionnel'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_unitaire',
            field=models.PositiveIntegerField(verbose_name='prix unitaire(USD$)'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='CoutUnitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaments.produit')),
            ],
        ),
    ]
