# Generated by Django 4.1 on 2022-10-22 13:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0019_alter_consmoy_options_alter_commande_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrmoy',
            name='mois',
            field=models.PositiveIntegerField(choices=[('01', 'janvier'), ('02', 'Fevrier'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Aout'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Decembre')], null=True, verbose_name='mois'),
        ),
        migrations.AddField(
            model_name='distrmoy',
            name='six_dernier_mois',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='consmoy',
            name='annee',
            field=models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2020)], verbose_name='annee'),
        ),
        migrations.AlterField(
            model_name='coutunitaire',
            name='cout',
            field=models.PositiveIntegerField(verbose_name='Cout unitaire USD$'),
        ),
        migrations.AlterField(
            model_name='coutunitaire',
            name='date_debut',
            field=models.DateField(verbose_name='Date debut'),
        ),
        migrations.AlterField(
            model_name='coutunitaire',
            name='date_fin',
            field=models.DateField(verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='distrmoy',
            name='annee',
            field=models.PositiveIntegerField(choices=[(2022, 2022), (2021, 2021), (2020, 2020)], verbose_name='annee'),
        ),
    ]
