# Generated by Django 4.1 on 2022-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0021_alter_distrmoy_six_dernier_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrmoy',
            name='six_dernier_mois',
            field=models.JSONField(default='{}'),
        ),
    ]
