# Generated by Django 4.1 on 2022-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0022_alter_distrmoy_six_dernier_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrmoy',
            name='annee',
            field=models.PositiveIntegerField(blank=True, choices=[(2022, 2022), (2021, 2021), (2020, 2020)], verbose_name='annee'),
        ),
        migrations.AlterField(
            model_name='distrmoy',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Distr. moyenne mensuelle'),
        ),
    ]
