# Generated by Django 4.1 on 2022-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0023_alter_distrmoy_annee_alter_distrmoy_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrmoy',
            name='six_dernier_mois',
            field=models.JSONField(default={}),
        ),
    ]
